# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Woo Suk (Paul) Choi
title: Ph.D candidate at Seoul National University
email: wschoi@bi.snu.ac.kr
website: cws7777.github.io

# Social links
twitter_username: facespics
github_username:  cws7777
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: paulchoi_63
linkedin_username: woosuk-paul-choi-36198494
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_wschoi.jpg
about_content: | # this will include new lines to allow paragraphs
A results-oriented AI Researcher currently pursuing an integrated MS/PhD at Seoul National University, building on a Bachelor's in Computer Engineering from the State University of New York (SUNY) at Buffalo. My background includes two years of hands-on research at the Korea Electronics Technology Institute (KETI), where I developed Deep Learning and Reinforcement Learning models for automated IoT systems and co-engineered an environmental sensor device for occupancy detection. At SNU, I have successfully managed high-impact, industry-sponsored projects. As the Project Manager for a collaboration with Samsung Electronics ("Samsung Beyond Limit"project), I led the development of an AI-based analysis system for semiconductor manufacturing processes. Subsequently, as Deputy Project Manager, I developed a "Learning by Asking" (LBA) agent for active knowledge acquisition.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
  Outside of research, I enjoy spending time on things that keep me energized and inspired:
   - Gaming (MMORPG(LostArk, Diablo II and IV), League of Legends, etc.)
   - Working out and staying active through weight training, basketball, and swimming
   - Watching sports like soccer(football), basketball, and baseball
   - Listening to music and discovering new artists
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
