# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Woo Suk (Paul) Choi
title: Master's degree at Seoul National University
email: wschoi@bi.snu.ac.kr
website: cws7777.github.io

# Social links
twitter_username: facespics
github_username:  cws7777
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: paulchoi_63
linkedin_username: woosuk-paul-choi-36198494
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile_wschoi.jpg
about_content: | # this will include new lines to allow paragraphs
  ▷ Currently on Master's degree for Neuroscience major in Biointelligence lab at Seoul National University.

  ▷ Worked at KETI (Korea Electronic Technology Institute) as research assistant. (Oct. 2016 - Jul. 2018)

  ▷ Graduated (B.S. in Computer Engineering) from University at Buffalo. (Class of 2016)
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in engineering, some of my other interests and hobbies are:
   - Gaming (League of Legends, Battleground)
   - Exercises (Weight-Training, Basketball, Swimming)
   - Music
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
